### ISSUE TITLE
Echolink Sounds

### ISSUE THREAD

**Issue by solomonbstoner** [rolandturner/9v1rs#10]
This table records the times I hear the phrase "Activating/Deactivating Echolink" when monitoring the repeater. I will edit this comment to add more records as and when I hear more instances of that phrase.

| Date | Time (SGT) | Audio Heard | Comments |
|---|---|---|---|
|Mar 2 2021|1039| "Echolink" | The audio did not mention "activating/deactivating". Just "Echolink" |

**Comment by rolandturner** [comment]
Thanks Solomon. This was an hour or two prior to [the recent changes](https://github.com/rolandturner/9v1rs/wiki/Maintenance-log), but is an unexpected sound.

The relevant log entries are:

    Mar  2 10:39:36 9v1rs svxlink[16757]: Spurious audio packet received from 54.197.42.167
    Mar  2 10:39:36 9v1rs svxlink[16757]: Incoming EchoLink connection from KI5BEJ (iPhone) at 54.197.42.167
    Mar  2 10:39:36 9v1rs svxlink[16757]: *** WARNING: Ignoring incoming connection from KI5BEJ since the IP address registered in the directory server (44.137.75.244) is not the same as the remote IP address (54.197.42.167) of the incoming connection
    Mar  2 10:39:37 9v1rs svxlink[16757]: Spurious audio packet received from 54.197.42.167
    Mar  2 10:39:37 9v1rs svxlink[16757]: Incoming EchoLink connection from KI5BEJ (iPhone) at 54.197.42.167
    Mar  2 10:39:37 9v1rs svxlink[16757]: *** WARNING: Ignoring incoming connection from KI5BEJ since the IP address registered in the directory server (44.137.75.244) is not the same as the remote IP address (54.197.42.167) of the incoming connection
    Mar  2 10:39:39 9v1rs svxlink[16757]: Spurious audio packet received from 54.197.42.167
    Mar  2 10:39:39 9v1rs svxlink[16757]: Incoming EchoLink connection from KI5BEJ (iPhone) at 54.197.42.167
    Mar  2 10:39:39 9v1rs svxlink[16757]: SimplexLogic: Activating module EchoLink...
    Mar  2 10:39:39 9v1rs svxlink[16757]: KI5BEJ: Accepting connection. EchoLink ID is 677757...
    Mar  2 10:39:39 9v1rs svxlink[16757]: KI5BEJ: EchoLink QSO state changed to CONNECTED
    Mar  2 10:39:39 9v1rs svxlink[16757]: Tx1: Turning the transmitter ON
    Mar  2 10:39:40 9v1rs svxlink[16757]: --- EchoLink info message received from KI5BEJ ---
    Mar  2 10:39:40 9v1rs svxlink[16757]: Station KI5BEJ
    Mar  2 10:39:40 9v1rs svxlink[16757]: iPhone User
    Mar  2 10:39:40 9v1rs svxlink[16757]: iPhone
    Mar  2 10:39:40 9v1rs svxlink[16757]: iPhone
    Mar  2 10:39:42 9v1rs svxlink[16757]: Tx1: Turning the transmitter OFF
    Mar  2 10:39:42 9v1rs svxlink[16757]: Rx1: The squelch is OPEN (6.75908)
    Mar  2 10:39:45 9v1rs svxlink[16757]: KI5BEJ: EchoLink QSO state changed to BYE_RECEIVED
    Mar  2 10:39:45 9v1rs svxlink[16757]: KI5BEJ: EchoLink QSO state changed to DISCONNECTED
    Mar  2 10:39:45 9v1rs svxlink[16757]: SimplexLogic: Deactivating module EchoLink...
    Mar  2 10:39:45 9v1rs svxlink[16757]: Rx1: The squelch is CLOSED (7.59843)

This would appear to be a normal connection to the service.
- Note that the Spurious/Ignoring messages are tied up with rough edges in EchoLink's design and are perfectly normal (audio streams aren't signed so the system relies on knowing about IP addresses, but that information takes time to propagate).
- The visit was brief (6 seconds!) but not otherwise unusual.

Hopefully the recent changes mean that future visits of this kind won't transmit voice messages.

**Comment by solomonbstoner** [comment]
Thank you for the update. Since your reply, I have not heard the announcement "(de)activating echolink" while monitoring the repeater.

**Comment by solomonbstoner** [comment]
Issue closed as the announcement in question has not been heard since the last comment
