### ISSUE TITLE
Abrupt Repeater Outage

### ISSUE THREAD

**Issue by kimberlychia92** [rolandturner/9v1rs#8]
The repeater ceased operation right in the middle of an ongoing QSO. About 30 minutes later the repeater resumed operation and what appeared to be the voice of an aged gentleman saying "maybe the repeater does not like the lingo used". The hypothesis is that the repeater host does not like the ongoing QSO and decided to shut down the repeater at his will. Attached is a recording for validation. Is such action supported by the society?

Question, are there any documented law or constitution that specify what form of language is acceptable on the repeater with the condition that proper station ID is done?

[Audio Recording.zip](https://github.com/rolandturner/9v1rs/files/5987257/Audio.Recording.zip)

**Comment by rolandturner** [comment]
Thanks for the report. Are you a licensed amateur operator? May I know your callsign please?

**Comment by rolandturner** [comment]
Unable to identify reporter.
